model {
  file: "model.sdf"
}
name: "Frozen_Olafs_In_Trouble_PopOMatic_Game"
description: "Frozen Olaf\'s In Trouble Pop-O-Matic Game"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Hasbro"
}
annotations {
  key: "gtin"
  value: "00630509276646"
}
annotations {
  key: "sku"
  value: "630509276646"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Board Games"
}
